fix: 반환값 수정
TeamMoHead/ModuGisang pull request #258
Opened 2024-12-21 07:08 UTC by GEUMDOHYEON

## #️⃣ Part

- [ ] FE
- [x] BE

## 📝 작업 내용

> 백엔드에서 프론트엔드로 전송하는 Response 값 수정

2024-12-21 07:17 UTC, pongpongie reviewed
귀찮겠지만 "챌린지 생성에 성공하였습니다" 처럼 문장으로 해주실수 있나여? 😙

2024-12-21 07:20 UTC, pongpongie commented
This pull request includes several changes to the `ChallengesController` in the `backend/src/challenges/challenges.controller.ts` file. The primary focus is on updating the controller methods to use the `@Res()` decorator from NestJS for sending HTTP responses directly.

Key changes include:

### HTTP Response Handling:

* Added the `@Res()` decorator to the `editChallenge`, `deleteChallenge`, `getChallengeResults`, and `challengeGiveUp` methods to handle HTTP responses directly. [[1]](diffhunk://#diff-586c9177dee73f018097204b905a27c2b062250a89f0d3fe462079330217db69L92-R105) [[2]](diffhunk://#diff-586c9177dee73f018097204b905a27c2b062250a89f0d3fe462079330217db69L114-R116) [[3]](diffhunk://#diff-586c9177dee73f018097204b905a27c2b062250a89f0d3fe462079330217db69R199-R210) [[4]](diffhunk://#diff-586c9177dee73f018097204b905a27c2b062250a89f0d3fe462079330217db69R248-R261)
* Modified the response logic within these methods to use `res.status(HttpStatus.<STATUS>).send(<message>)` for sending responses. [[1]](diffhunk://#diff-586c9177dee73f018097204b905a27c2b062250a89f0d3fe462079330217db69L92-R105) [[2]](diffhunk://#diff-586c9177dee73f018097204b905a27c2b062250a89f0d3fe462079330217db69L114-R116) [[3]](diffhunk://#diff-586c9177dee73f018097204b905a27c2b062250a89f0d3fe462079330217db69L126-R131) [[4]](diffhunk://#diff-586c9177dee73f018097204b905a27c2b062250a89f0d3fe462079330217db69R248-R261)

### Error Handling:

* Updated error handling in the `challengeGiveUp` method to throw an `HttpException` with detailed status and error message.

These changes improve the consistency and clarity of HTTP response handling in the `ChallengesController`.

2024-12-22 05:23 UTC, pongpongie approved these changes
고생하셨습니다이~

2024-12-23 07:38 UTC, won0845 requested changes

2024-12-23 07:38 UTC, won0845 commented on backend/src/challenges/challenges.controller.ts
> +        .send('챌린지 수정에 성공하였습니다.');
HttpStatus.OK (200)
수정된 리소스에 대한 데이터를 클라이언트에게 반환할 경우 적합합니다.
예: 수정된 챌린지의 정보를 JSON으로 반환.

HttpStatus.NO_CONTENT (204)
수정 작업은 성공했지만 클라이언트에 반환할 추가 데이터가 없을 경우 적합합니다.
예: 클라이언트가 추가 데이터를 필요로 하지 않을 때.

HttpStatus.CREATED (201)
기존 리소스의 수정이 아닌, 새로운 리소스가 생성된 결과를 나타낼 때만 사용합니다.
예: 수정이 아니라 새로운 챌린지 복사본이 생성된 경우.

라고합니다. 201은 create시에만 사용한다고 하니 OK 또는 NO_CONTENT로 바꾸는게 어떨까 함이

2024-12-23 07:38 UTC, won0845 commented on backend/src/challenges/challenges.controller.ts
> +        .status(HttpStatus.CREATED)
이 내용도 Create가 아닌 200 OK로 바꿔야 할 거 같슴둥

2024-12-23 07:38 UTC, won0845 commented on backend/src/challenges/challenges.controller.ts
> +      );
이 내용은 HttpStatus.INTERNAL_SERVER_ERROR, 와 HttpStatus.BAD_REQUEST 왜 서로 Status가 다른지 궁금합니다.

2024-12-23 07:42 UTC, won0845 requested changes
.

2024-12-23 14:49 UTC, won0845 approved these changes

2024-12-23 14:50 UTC, merged